server:
  port: 8081
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  liquibase:
    url: jdbc:postgresql://localhost:5432/polardb_order
    change-log: /db/changelog/changelog-master.yaml
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

polar:
  catalog-service-uri: http://localhost:8080