apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-postgres-order
  labels:
    db: polar-postgres-order
spec:
  selector:
    matchLabels:
      db: polar-postgres-order
  template:
    metadata:
      labels:
        db: polar-postgres-order
    spec:
      containers:
        - name: polar-postgres-order
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: polardb_order
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: polar-postgres-order
  labels:
    db: polar-postgres-order
spec:
  type: ClusterIP
  selector:
    db: polar-postgres-order
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432